version: "2"
linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exptostd
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - govet
    - ineffassign
    - intrange
    - loggercheck
    - mirror
    - misspell
    - nilerr
    - nolintlint
    - nilnesserr
    - nilnil
    - noctx
    - paralleltest
    - perfsprint
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
  settings:
    goconst:
      min-len: 5
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - appendAssign
      settings:
        ifElseChain:
          minThreshold: 3
    misspell:
      locale: US
    paralleltest:
      ignore-missing: true
    revive:
      rules:
        - name: blank-imports
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/capnspacehook/dep-inspector)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
