version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - durationcheck
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - nilerr
    - nilnil
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
  settings:
    asasalint:
      exclude:
        - append
    errcheck:
      exclude-functions:
        - io.Copy(ioutil.Discard)
        - io.CopyN(ioutil.Discard)
        - (go.uber.org/zap/zapcore.ObjectEncoder).AddObject
    errorlint:
      errorf: false
    gocritic:
      enabled-checks:
        - truncateCmp
        - sqlQuery
      enabled-tags:
        - diagnostic
      disabled-tags:
        - experimental
        - opinionated
        - performance
        - style
    govet:
      disable:
        - composites
    reassign:
      patterns:
        - .*
    revive:
      rules:
        - name: blank-imports
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
        text: 'appendAssign:'
      - linters:
          - gocritic
        text: 'deprecatedComment:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
